spring:
  datasource:
      url: jdbc:mysql://localhost:3306/springboot-shiro-vue?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=GMT%2B8
      username: root
      password: shuang
mybatis:
   mapperLocations: classpath:/mapper/*.xml
